---
services:

  resellerapp:
    image: resellerapp
    build:
        dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/resellerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my-secret-pw
    networks:
        - backend
    restart: on-failure

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=resellerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpas
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: on-failure

volumes:
  mysql-data:

networks:
  backend:
